/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import arbolNario.listaGeneralizada.ArbolNarioListaGeneralizada;
import arbol.binario.listaligada.busqueda.avl.ArbolAVL;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sistema_contactos.BD_contactos.BD_contactos;
import sistema_contactos.BD_identificador.BD_identificador;
import sistema_contactos.contacto.Contacto;
/**
 *
 * @author cami0
 */
public class JFramePrincipal extends javax.swing.JFrame {

     static BD_identificador identificador;
     static BD_contactos contactos;
    /**
     * Creates new form JFrame
     */
    public JFramePrincipal() throws IOException {
        initComponents();
        identificador = new BD_identificador();
        contactos = new BD_contactos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButtonIngresar = new javax.swing.JButton();
        jButtonConsultar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        agregarIden = new javax.swing.JButton();
        guardarBD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("ACCIÓN A REALIZAR:");

        jButtonIngresar.setText("INGRESAR UN NUEVO CONTACTO");
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });

        jButtonConsultar.setText("CONSULTAR LOS CONTACTOS DE ALGUIEN");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        jLabel1.setText("BIENVENIDO");

        agregarIden.setText("AGREGAR CONTACTO AL IDENTIFICADOR");
        agregarIden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarIdenMouseClicked(evt);
            }
        });
        agregarIden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarIdenActionPerformed(evt);
            }
        });

        guardarBD.setText("GUARDAR BD DE CONTACTOS");
        guardarBD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarBDMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(201, 201, 201))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jButtonIngresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jButtonConsultar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(agregarIden))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(guardarBD)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(jLabel3)
                .addGap(35, 35, 35)
                .addComponent(jButtonIngresar)
                .addGap(29, 29, 29)
                .addComponent(jButtonConsultar)
                .addGap(18, 18, 18)
                .addComponent(agregarIden)
                .addGap(18, 18, 18)
                .addComponent(guardarBD)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        JFrameConsultar ventanaConsulta = new JFrameConsultar();
        ventanaConsulta.setVisible(true);
        
        dispose();
        
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed
        
        try {
            JFrameIngresar ventanaIngreso = new JFrameIngresar();
            ventanaIngreso.setVisible(true);
            dispose();
            
        } catch (IOException ex) {
            Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonIngresarActionPerformed

    private void agregarIdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarIdenActionPerformed

    }//GEN-LAST:event_agregarIdenActionPerformed

    private void guardarBDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarBDMouseClicked
        // TODO add your handling code here:
        JFramePrincipal.contactos.guardarDatos();
    }//GEN-LAST:event_guardarBDMouseClicked

    private void agregarIdenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarIdenMouseClicked
        // TODO add your handling code here:
        String name = JOptionPane.showInputDialog("Ingrese en nombre del nuevo contacto");
        int cel = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el número del contacto"));
        Contacto nuevo = new Contacto(cel,name);
         try {
             JFramePrincipal.identificador.agregarContacto(nuevo);
         } catch (IOException ex) {
             Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_agregarIdenMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFramePrincipal().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarIden;
    private javax.swing.JButton guardarBD;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables


}
